Repository itlize-proj/CostManager_Backend, pull requests merged in 2022-01, with the labels that each got.

#12 Refactor complete
  GroupProject/.gitignore
  GroupProject/src/main/java/com/example/groupproject/entities/Project.java
  GroupProject/src/main/java/com/example/groupproject/entities/ProjectDetail.java
  GroupProject/src/main/java/com/example/groupproject/entities/Resource.java
  GroupProject/src/main/java/com/example/groupproject/entities/ResourceColumn.java
  GroupProject/src/main/java/com/example/groupproject/entities/ResourceToProject.java
  GroupProject/src/main/java/com/example/groupproject/entities/User.java
  GroupProject/src/main/java/com/example/groupproject/repositories/ProjectDetailRepository.java
  GroupProject/src/main/java/com/example/groupproject/repositories/ProjectDetailsDAO.java
  GroupProject/src/main/java/com/example/groupproject/repositories/ProjectRepository.java
  GroupProject/src/main/java/com/example/groupproject/repositories/ResourceColumnDAO.java
  GroupProject/src/main/java/com/example/groupproject/repositories/ResourceColumnRepository.java
  GroupProject/src/main/java/com/example/groupproject/repositories/ResourceRepository.java
  GroupProject/src/main/java/com/example/groupproject/repositories/ResourceToProjectRepository.java
  GroupProject/src/main/java/com/example/groupproject/repositories/ResourcesDAO.java
  GroupProject/src/main/java/com/example/groupproject/repositories/UserRepository.java
  GroupProject/src/main/java/com/example/groupproject/services/ProjectDetailService.java
  GroupProject/src/main/java/com/example/groupproject/services/ProjectDetailsService.java
  GroupProject/src/main/java/com/example/groupproject/services/ResourceColumnService.java
  GroupProject/src/main/java/com/example/groupproject/services/ResourceService.java
  GroupProject/src/main/java/com/example/groupproject/services/ResourceToProjectService.java
  GroupProject/src/main/java/com/example/groupproject/services/serviceImp/ProjectDetailServiceImp.java
  GroupProject/src/main/java/com/example/groupproject/services/serviceImp/ProjectDetailsServiceImp.java
  GroupProject/src/main/java/com/example/groupproject/services/serviceImp/ProjectServiceImp.java
  GroupProject/src/main/java/com/example/groupproject/services/serviceImp/ResourcesServiceImp.java
  GroupProject/src/test/java/com/example/groupproject/ResourceColumnTest.java
  GroupProject/src/test/java/com/example/groupproject/ResourceToProjectTests.java
  GroupProject/src/test/java/com/example/groupproject/repositories/ProjectDetailRepositoryTest.java
  GroupProject/src/test/java/com/example/groupproject/repositories/ProjectDetailsDAOTest.java
  GroupProject/src/test/java/com/example/groupproject/repositories/ProjectRepositoryTest.java
  GroupProject/src/test/java/com/example/groupproject/repositories/ResourceColumnRepositoryTest.java
Labels: enhancement

#14 move all folders up one dir
  .gitignore
  .idea/vcs.xml
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  GroupProject/.gitignore
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/example/groupproject/GroupProjectApplication.java
  src/main/java/com/example/groupproject/entities/FormulaType.java
  src/main/java/com/example/groupproject/entities/Project.java
  src/main/java/com/example/groupproject/entities/ProjectDetail.java
  src/main/java/com/example/groupproject/entities/Resource.java
  src/main/java/com/example/groupproject/entities/ResourceColumn.java
  src/main/java/com/example/groupproject/entities/ResourceToProject.java
  src/main/java/com/example/groupproject/entities/Role.java
  src/main/java/com/example/groupproject/entities/User.java
  src/main/java/com/example/groupproject/repositories/ProjectDetailRepository.java
  src/main/java/com/example/groupproject/repositories/ProjectRepository.java
  src/main/java/com/example/groupproject/repositories/ResourceColumnRepository.java
  src/main/java/com/example/groupproject/repositories/ResourceRepository.java
  src/main/java/com/example/groupproject/repositories/ResourceToProjectRepository.java
  src/main/java/com/example/groupproject/repositories/UserRepository.java
  src/main/java/com/example/groupproject/services/ProjectDetailService.java
  src/main/java/com/example/groupproject/services/ProjectService.java
  src/main/java/com/example/groupproject/services/ResourceColumnService.java
  src/main/java/com/example/groupproject/services/ResourceService.java
  src/main/java/com/example/groupproject/services/ResourceToProjectService.java
  src/main/java/com/example/groupproject/services/UserService.java
  src/main/java/com/example/groupproject/services/serviceImp/ProjectDetailServiceImp.java
  src/main/java/com/example/groupproject/services/serviceImp/ProjectServiceImp.java
  src/main/java/com/example/groupproject/services/serviceImp/ResourcesServiceImp.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/example/groupproject/GroupProjectApplicationTests.java
  src/test/java/com/example/groupproject/ResourceColumnTest.java
  src/test/java/com/example/groupproject/ResourceToProjectTests.java
  src/test/java/com/example/groupproject/repositories/ProjectDetailRepositoryTest.java
  src/test/java/com/example/groupproject/repositories/ProjectRepositoryTest.java
  src/test/java/com/example/groupproject/repositories/ResourceColumnRepositoryTest.java
Labels: fixes

#17 Finish Services
  .gitignore
  src/main/java/com/example/groupproject/controllers/ProjectDetailController.java
  src/main/java/com/example/groupproject/services/serviceImp/ResourceColumnServiceImp.java
  src/main/java/com/example/groupproject/services/serviceImp/ResourceToProjectServiceImp.java
  src/main/java/com/example/groupproject/services/serviceImp/UserServiceImp.java
  src/main/resources/application.yml
Labels: enhancement

#23 resourceController completed
  src/main/java/com/example/groupproject/controllers/ResourceController.java
  src/main/java/com/example/groupproject/entities/Resource.java
  src/main/java/com/example/groupproject/entities/User.java
  src/main/java/com/example/groupproject/security/SpringBootSecurityConfiguration.java
  src/main/java/com/example/groupproject/services/ResourceService.java
  src/main/java/com/example/groupproject/services/serviceImp/ResourcesServiceImp.java
  src/main/resources/application.properties
  src/test/java/com/example/groupproject/repositories/ProjectDetailRepositoryTest.java
  src/test/java/com/example/groupproject/repositories/ProjectRepositoryTest.java
Labels: enhancement, fixes

#26 controllers done - fixed error with names
  src/main/java/com/example/groupproject/controllers/ProjectController.java
  src/main/java/com/example/groupproject/controllers/ProjectDetailController.java
  src/main/java/com/example/groupproject/controllers/ResourceColumnController.java
  src/main/java/com/example/groupproject/controllers/ResourceToProjectController.java
  src/main/java/com/example/groupproject/services/serviceImp/ProjectDetailServiceImp.java
  src/main/java/com/example/groupproject/services/serviceImp/ProjectServiceImp.java
  src/main/java/com/example/groupproject/services/serviceImp/ResourceToProjectServiceImp.java
Labels: bug
